# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-location
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: local-wip-templates
  title: Local WIP Templates
spec:
  type: file
  targets:
    - ./kotlin-api-template/catalog-info.yaml